# Generated by Django 2.2.7 on 2020-09-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promise',
            name='storelist',
            field=models.TextField(null=True),
        ),
    ]
