# Generated by Django 2.2.7 on 2020-09-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
