# Generated by Django 2.2.7 on 2020-09-22 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_auto_20200921_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
